import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Atlassian Datacenter End of Life Alternatives: A Guide for Defense Industry and Security-Focused Companies',
  description: 'Jira and Confluence alternatives for defense industry and security-focused companies that cannot migrate to Cloud after Atlassian Datacenter end of life. Detailed analysis of XWiki, BlueSpice, Wiki.js, MediaWiki and more.',
  keywords: [
    'Atlassian Datacenter',
    'Jira alternatives',
    'Confluence alternatives',
    'XWiki',
    'BlueSpice',
    'Wiki.js',
    'MediaWiki',
    'defense industry',
    'on-premise wiki',
    'self-hosted project management',
    'security-focused software',
    'Atlassian migration',
    'enterprise wiki',
    'open source wiki',
    'enterprise documentation',
    'project management tools',
    'Atlassian end of life',
    'data sovereignty',
    'compliance',
    'GDPR compliant wiki'
  ],
  authors: [{ name: 'Virtual Riddle Blog Team' }],
  creator: 'Virtual Riddle',
  publisher: 'Virtual Riddle',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://virtualriddle.com'),
  alternates: {
    canonical: '/blog/atlassian-datacenter-alternatives',
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'article',
    locale: 'en_US',
    url: 'https://virtualriddle.com/blog/atlassian-datacenter-alternatives',
    title: 'Atlassian Datacenter End of Life Alternatives: A Guide for Defense Industry and Security-Focused Companies',
    description: 'Jira and Confluence alternatives for companies that cannot migrate to Cloud after Atlassian Datacenter end of life. XWiki, BlueSpice, Wiki.js, MediaWiki detailed analysis.',
    siteName: 'Virtual Riddle',
    publishedTime: '2026-01-07T00:00:00.000Z',
    modifiedTime: '2026-01-07T00:00:00.000Z',
    authors: ['Virtual Riddle Blog Team'],
    section: 'Digital Transformation',
    tags: ['Atlassian', 'Jira', 'Confluence', 'Alternatives', 'Defense Industry', 'Security'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Atlassian Datacenter End of Life Alternatives',
    description: 'Jira and Confluence alternatives for defense industry and security-focused companies. XWiki, BlueSpice, Wiki.js, MediaWiki detailed analysis.',
    creator: '@virtualriddle',
  },
  other: {
    'article:author': 'Virtual Riddle Blog Team',
    'article:published_time': '2026-01-07T00:00:00.000Z',
    'article:modified_time': '2026-01-07T00:00:00.000Z',
    'article:section': 'Digital Transformation',
    'article:tag': 'Atlassian,Datacenter,Alternatives,Defense Industry,Security',
    'reading-time': '20',
    'word-count': '4000',
  }
};
