import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Working with Claude Connected to Atlassian: The MCP Revolution',
  description: 'Thanks to Atlassian\'s new Remote MCP Server, you can directly access your Jira and Confluence data with Claude and create AI-powered workflows. This integration increases team efficiency while eliminating knowledge silos.',
  keywords: [
    'Claude',
    'Atlassian MCP',
    'Model Context Protocol',
    'Jira AI integration',
    'Confluence AI',
    'artificial intelligence',
    'AI assistant',
    'Atlassian consulting',
    'Remote MCP Server',
    'Anthropic Claude',
    'AI workflows',
    'enterprise AI',
    'Atlassian automation',
    'AI-powered project management',
    'Claude integration'
  ],
  authors: [{ name: 'Virtual Riddle Blog Team' }],
  creator: 'Virtual Riddle',
  publisher: 'Virtual Riddle',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://virtualriddle.com'),
  alternates: {
    canonical: '/blog/claude-atlassian-mcp-entegrasyonu',
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'article',
    locale: 'en_US',
    url: 'https://virtualriddle.com/blog/claude-atlassian-mcp-entegrasyonu',
    title: 'Working with Claude Connected to Atlassian: The MCP Revolution',
    description: 'Thanks to Atlassian\'s new Remote MCP Server, you can directly access your Jira and Confluence data with Claude and create AI-powered workflows.',
    siteName: 'Virtual Riddle',
    publishedTime: '2025-09-01T00:00:00.000Z',
    modifiedTime: '2025-09-01T00:00:00.000Z',
    authors: ['Virtual Riddle Blog Team'],
    section: 'Artificial Intelligence',
    tags: ['Claude', 'Atlassian', 'MCP', 'AI', 'Artificial Intelligence', 'Integration'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Working with Claude Connected to Atlassian: The MCP Revolution',
    description: 'Thanks to Atlassian\'s new Remote MCP Server, you can directly access your Jira and Confluence data with Claude and create AI-powered workflows.',
    creator: '@virtualriddle',
  },
  other: {
    'article:author': 'Virtual Riddle Blog Team',
    'article:published_time': '2025-09-01T00:00:00.000Z',
    'article:modified_time': '2025-09-01T00:00:00.000Z',
    'article:section': 'Artificial Intelligence',
    'article:tag': 'Claude,Atlassian,MCP,AI,Artificial Intelligence,Integration',
    'reading-time': '10',
    'word-count': '2500',
  }
};
